### ISSUE TITLE
delete() method returns 500

### ISSUE THREAD

**Issue by jackytj** [Explosion-Scratch/claude-unofficial-api#44]
![image](https://github.com/Explosion-Scratch/claude-unofficial-api/assets/42001748/7c08bb57-1eb9-432a-b882-59d2cddef933)

**Comment by Explosion-Scratch** [comment]
<img width="194" alt="image" src="https://github.com/Explosion-Scratch/claude-unofficial-api/assets/61319150/f818e6e2-e73f-4f8b-a3d5-8a2751cd9ed8">
It's still working for me, internal server error is Claude's fault though. There was a period a few days ago where it was down so that might have been the cause. Please tell me if this is working on the web ui but not in the cli and I'll investigate further
