### ISSUE TITLE
Can I install it in google scripts?

### ISSUE THREAD

**Issue by sdimantsd** [Explosion-Scratch/claude-unofficial-api#57]
How can I do it?

**Comment by Explosion-Scratch** [comment]
@sdimantsd I regret to inform you that it doesn't currently work (See #51) due to Claude's server side changes. That being said, you can use the [main script](https://github.com/Explosion-Scratch/claude-unofficial-api/blob/main/index.js) anywhere. Just paste it somewhere, or load the URL from [JSDelivr](https://cdn.jsdelivr.net/gh/Explosion-Scratch/claude-unofficial-api/index.js) in a script tag or something.

**Comment by sdimantsd** [comment]
OK, Thanks
